apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/ansible/awx-operator/0.10.0/deploy/awx-operator.yaml
namespace: awx
