set interfaces ethernet eth0 address '1.1.1.2/30'
set interfaces ethernet eth0 description 'WAN1'
set interfaces ethernet eth0 duplex 'auto'
set interfaces ethernet eth0 hw-id '52:54:00:60:6c:3c'
set interfaces ethernet eth0 smp_affinity 'auto'
set interfaces ethernet eth0 speed 'auto'
set interfaces ethernet eth1 address '172.24.0.1/24'
set interfaces ethernet eth1 description 'LAN'
set interfaces ethernet eth1 duplex 'auto'
set interfaces ethernet eth1 hw-id '52:54:00:3c:f2:6e'
set interfaces ethernet eth1 smp_affinity 'auto'
set interfaces ethernet eth1 speed 'auto'
set interfaces ethernet eth1 vif 2 address '172.24.2.1/24'
set interfaces ethernet eth1 vif 2 description 'Kubernetes 1.6 Hosts Network'
set interfaces loopback 'lo'
set protocols bgp 64512 neighbor 1.1.1.1 ebgp-multihop '2'
set protocols bgp 64512 neighbor 1.1.1.1 remote-as '64511'
set protocols bgp 64512 neighbor 1.1.1.1 update-source '1.1.1.2'
set protocols bgp 64512 network '172.24.0.0/24'
set protocols bgp 64512 network '172.24.2.0/24'
set protocols bgp 64512 parameters router-id '1.1.1.2'
set protocols 'static'
set service dhcp-server disabled 'false'
set service dhcp-server shared-network-name LAN authoritative 'disable'
set service dhcp-server shared-network-name LAN subnet 172.24.0.0/24 default-router '172.24.0.1'
set service dhcp-server shared-network-name LAN subnet 172.24.0.0/24 dns-server '172.24.0.1'
set service dhcp-server shared-network-name LAN subnet 172.24.0.0/24 lease '86400'
set service dhcp-server shared-network-name LAN subnet 172.24.0.0/24 start 172.24.0.200 stop '172.24.0.254'
set service dns forwarding cache-size '0'
set service dns forwarding listen-on 'eth1'
set service dns forwarding name-server '192.168.114.14'
set service dns forwarding name-server '192.168.114.15'
set service ssh port '22'
set system config-management commit-revisions '20'
set system console device ttyS0 speed '9600'
set system host-name 'dc-2-aggr-sw-1'
set system login user vyos authentication encrypted-password '$1$vPPMAjzJ$ap2pmPaUekJRf6VElrSzs0'
set system login user vyos authentication plaintext-password ''
set system login user vyos level 'admin'
set system ntp server '0.pool.ntp.org'
set system ntp server '1.pool.ntp.org'
set system ntp server '2.pool.ntp.org'
set system package auto-sync '1'
set system package repository community components 'main'
set system package repository community distribution 'helium'
set system package repository community password ''
set system package repository community url 'http://packages.vyos.net/vyos'
set system package repository community username ''
set system syslog global facility all level 'notice'
set system syslog global facility protocols level 'debug'
set system time-zone 'UTC'
